# Generated by Django 4.2 on 2025-02-26 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cheese_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meat_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_address', models.TextField()),
                ('pay_method', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Credit Card', 'Credit Card')], max_length=20)),
                ('mobile_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number.', regex='^01[3-9]\\d{8}$')])),
                ('order_status', models.CharField(choices=[('Processing', 'Processing'), ('Packing', 'Packing'), ('Ready to Deliver', 'Ready to Deliver'), ('Delivered', 'Delivered')], default='Processing', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
